export const imagePaths = {
	attributes: {
		attack: "/images/attributes/attack.png",
		defense: "/images/attributes/defense.png",
	},
	badges: {
		vip: "/images/badges/vip.png",
		topAlms: "/images/badges/S_Top1Alms.png",
		topBeatUp: "/images/badges/S_Top1BeatUp.png",
		topBribery: "/images/badges/S_Top1Bribery.png",
		topCasinoProfit: "/images/badges/S_Top1CasinoProfit.png",
		topCasinoWR: "/images/badges/S_Top1CasinoWR.png",
		topEscapes: "/images/badges/S_Top1Escapes.png",
		topGang: "/images/badges/S_Top1Gang.png",
		topHospital: "/images/badges/S_Top1Hospital.png",
		topInvestments: "/images/badges/S_Top1Investments.png",
		topJobs: "/images/badges/S_Top1Jobs.png",
		top1Money: "/images/badges/S_Top1Money.png",
		top2Money: "/images/badges/S_Top2Money.png",
		top3Money: "/images/badges/S_Top3Money.png",
		topRobberyProfit: "/images/badges/S_Top1RobberyProfit.png",
		topRobberyQuantity: "/images/badges/S_Top1RobberyQuantity.png",
		topRooster: "/images/badges/S_Top1Rooster.png",
		topScavenge: "/images/badges/S_Top1Scavenge.png",
		topSpender: "/images/badges/S_Top1Spender.png",
	},
	brand: {
		logo: "/images/brand/CrossRoadsLogo.png",
	},
	classes: {
		none: "/images/classes/0_None.png",
		thief: "/images/classes/1_Thief.png",
		assassin: "/images/classes/2_Assassin.png",
		entrepreneur: "/images/classes/3_Entrepreneur.png",
		hobo: "/images/classes/4_Hobo.png",
		mafioso: "/images/classes/5_Mafioso.png",
		attorney: "/images/classes/6_Attorney.png",
	},
	investments: {
		churrosCart: "/images/investments/1_churros_cart.png",
		crackDen: "/images/investments/2_crack_den.png",
		bocceCourt: "/images/investments/3_bocce_court.png",
		veganRestaurant: "/images/investments/4_vegan_restaurant.png",
		golfClub: "/images/investments/5_golf_club.png",
		vehicleManufacturer: "/images/investments/6_vehicle_manufacturer.png",
		underdevelopedCountry: "/images/investments/7_underdeveloped_country.png",
		religiousCult: "/images/investments/8_religious_cult.png",
		starGalaxy: "/images/investments/9_star_galaxy.png",
	},
	situations: {
		beatup: "/images/situations/beatup.png",
		casino: "/images/situations/casino.png",
		dead: "/images/situations/dead.png",
		defendingInvestment: "/images/situations/defending-investment.png",
		gangAction: "/images/situations/gang-action.png",
		hospital: "/images/situations/hospital.png",
		idling: "/images/situations/idling.png",
		job: "/images/situations/job.png",
		prison: "/images/situations/prison.png",
		robbery: "/images/situations/robbery.png",
		scavenging: "/images/situations/scavenging.png",
		wanted: "/images/situations/wanted.png",
	},
	uiElements: {
		inventory: "/images/ui_elements/inventory.png",
		vaultCasino: "/images/ui_elements/CasinoVault.png",
		vaultBank: "/images/ui_elements/CentralBank.png",
		daily: "/images/ui_elements/Heads.png",
		alms: "/images/ui_elements/Alms.png",
		shop: "/images/ui_elements/Shop.png",
		blackMarket: "/images/ui_elements/BlackMarket.png",
		escape: "/images/ui_elements/Escape.png",
		react: "/images/ui_elements/React.png",
		specialCoin: "/images/ui_elements/SpecialCoin.webp",
	},
	locations: {
		oldLady: "/images/locations/OldLady_.png",
		groceryStore: "/images/locations/GroceryStore_2.png",
		gasStation: "/images/locations/GasStation_.png",
		jewelry: "/images/locations/Jewelry_.png",
		smallBank: "/images/locations/SmallBank.png",
		italianMafia: "/images/locations/ItalianMafia_.png",
		armyDepot: "/images/locations/ArmyDepot_.png",
		jacobiPalace: "/images/locations/JacobiPalace_.png",
	},
} as const;

export type ImagePath = {
	[Category in keyof typeof imagePaths]: (typeof imagePaths)[Category][keyof (typeof imagePaths)[Category]];
}[keyof typeof imagePaths];
